algoritmo "aleatorio para exercicios"

var
i, aleatorioMax, aleatorioMin, incremento: inteiro
inicio
repita
   aleatorio 1, 100
   leia (aleatorioMax)
   leia (aleatorioMin)
   aleatorio off
ate aleatorioMax >= aleatorioMin

aleatorio 1,5
leia(incremento)
aleatorio off
limpatela

para i de aleatorioMin ate aleatorioMax passo incremento faca
   escreval (i)
fimpara
fimalgoritmo
