algoritmo "trabalhando com tipos"

var
palavra1, palavra2, palavra3: literal
numero1, numero2, numero3: real
inicio
escreval("Palavra 1: ")
leia(palavra1)

escreval("Palavra 2: ")
leia(palavra2)


escreval("Numero 1: ")
leia(numero1)


escreval("Numero 2: ")
leia(numero2)

palavra3 <- palavra1 + " " + palavra2
numero3 <- numero1 * numero2 /2
escreval(palavra3)
escreval(numero3)
fimalgoritmo
